spring:
  application:
    name: spring-api-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/auth/** # '/api' 추가
            filters:
              - StripPrefix=1       # '/api' 제거 필터 추가

          - id: user-service
            uri: http://localhost:8082
            predicates:
              - Path=/api/v1/users/** # '/api' 추가
            filters:
              - StripPrefix=1         # '/api' 제거 필터 추가

          - id: application-service
            uri: http://localhost:8089
            predicates:
              - Path=/api/v1/applications/** # '/api' 추가
            filters:
              - StripPrefix=1         # '/api' 제거 필터 추가

          - id: announcement-service
            uri: http://localhost:8084
            predicates:
              - Path=/api/v1/announcements/** # '/api' 추가
            filters:
              - StripPrefix=1         # '/api' 제거 필터 추가

          - id: pet-service
            uri: http://localhost:8085
            predicates:
              - Path=/api/v1/pets/** # '/api' 추가
            filters:
              - StripPrefix=1         # '/api' 제거 필터 추가

jwt:
  secret: "hellopethellopethellopethellopethellopethellopethellopethellopethellopethellopethellopet"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
